language: python
matrix:
  include:
    - os: linux
      python: 3.5
      env:
        - CIBW_BUILD: cp35-*
    - os: linux
      python: 3.6
      env:
        - CIBW_BUILD: cp36-*
    - os: linux
      python: 3.7
      env:
        - CIBW_BUILD: cp37-*
    - os: linux
      python: 3.8
      env:
        - CIBW_BUILD: cp38-*
    - os: osx
      language: shell
      env:
        - PYENV_VERSION: 3.5-dev
        - CIBW_BUILD: cp35-*
        - HOMEBREW_INSTALL_CLEANUP: 0
    - os: osx
      language: shell
      env:
        - PYENV_VERSION: 3.6-dev
        - CIBW_BUILD: cp36-*
        - HOMEBREW_INSTALL_CLEANUP: 0
    - os: osx
      language: shell
      env:
        - PYENV_VERSION: 3.7-dev
        - CIBW_BUILD: cp37-*
        - HOMEBREW_INSTALL_CLEANUP: 0
    - os: osx
      language: shell
      env:
        - PYENV_VERSION: 3.8-dev
        - CIBW_BUILD: cp38-*
        - HOMEBREW_INSTALL_CLEANUP: 0
    - os: windows
      language: shell
      env:
        - PYENV_VERSION: 3.5.9
        - PYENV_PATH: "/c/Python35"
        - CIBW_BUILD: cp35-*
      cache:
        directories:
          - "$HOME/AppData/Local/Temp/chocolatey"
          - "/C/tools/msys64"
          - "$PYENV_PATH"
    - os: windows
      language: shell
      env:
        - PYENV_VERSION: 3.6.11
        - PYENV_PATH: "/c/Python36"
        - CIBW_BUILD: cp36-*
      cache:
        directories:
          - "$HOME/AppData/Local/Temp/chocolatey"
          - "/C/tools/msys64"
          - "$PYENV_PATH"
    - os: windows
      language: shell
      env:
        - PYENV_VERSION: 3.7.8
        - PYENV_PATH: "/c/Python37"
        - CIBW_BUILD: cp37-*
      cache:
        directories:
          - "$HOME/AppData/Local/Temp/chocolatey"
          - "/C/tools/msys64"
          - "$PYENV_PATH"
    - os: windows
      language: shell
      env:
        - PYENV_VERSION: 3.8.5
        - PYENV_PATH: "/c/Python38"
        - CIBW_BUILD: cp38-*
      cache:
        directories:
          - "$HOME/AppData/Local/Temp/chocolatey"
          - "/C/tools/msys64"
          - "$PYENV_PATH"

before_install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          sudo apt install -y autoconf automake autopoint libtool
          pip install -U pip
          python --version
          ;;
        osx)
          brew install autoconf automake libtool gettext
          brew link gettext --force
          ## Hack to fix mac builds on XCode 11: https://github.com/blatinier/pyhunspell/issues/33
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
          eval "$(pyenv init -)"
          pyenv install $PYENV_VERSION
          pyenv global $PYENV_VERSION
          pyenv rehash
          pip install -U pip
          python --version
          ;;
        windows)
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco uninstall -y mingw
          choco upgrade --no-progress -y msys2
          export msys2='cmd //C RefreshEnv.cmd '
          export msys2+='& set MSYS=winsymlinks:nativestrict '
          export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
          export msys2+=" -msys2 -c "\"\$@"\" --"
          $msys2 pacman --sync --noconfirm --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool gcc
          ## Install more MSYS2 packages from https://packages.msys2.org/base here
          taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
          export PATH=/C/tools/msys64/mingw64/bin:/C/tools/msys64/usr/bin:$PATH
          export MAKE=mingw32-make  # so that Autotools can find it
          choco install python --version $PYENV_VERSION
          export PATH="$PYENV_PATH:$PYENV_PATH/Scripts:$PATH"
          pip install -U pip
          python --version
          ;;
      esac

before_cache:
  - |-
      case $TRAVIS_OS_NAME in
        windows)
          # https://unix.stackexchange.com/a/137322/107554
          $msys2 pacman --sync --clean --noconfirm
          ;;
      esac

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -r requirements-test.txt
  - pip install cibuildwheel
  - touch .cibuildwheel
  - python setup.py build
  - pip install .

script:
  - python -m pytest -vv
  # Remove the .so our build generates. See: https://github.com/joerick/cibuildwheel/issues/139
  - rm hunspell/*.so
  - python -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python -m twine upload --skip-existing wheelhouse/*;
    fi

notifications:
  email:
    recipients:
      - mseal007@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    - TWINE_USERNAME=__token__
